### PR TITLE
Solution language cpp

### PR DESCRIPTION
**Pull request by gpriya32**
-Heapsort
-subset sum problem gfg

### CODE REVIEW

**Comment by gpriya32** [comment]
C++ solutions

**Comment by gpriya32** [comment]
BellmanFordAlgo

**Comment by MilindGupta-Creator** [comment]
Great well done.

**Comment by gpriya32** [comment]
Hi! your repository is not valid for hactoberfest?

**Comment by gpriya32** [comment]
Please label that as hacktoberfest accepted. :)

**Pull request merged**
